# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Specscore < Formula
  desc "SpecScore CLI — lint, validate, and navigate Markdown specifications."
  homepage "https://specscore.md"
  version "0.15.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/specscore/specscore-cli/releases/download/v0.15.0/specscore_0.15.0_darwin_amd64.tar.gz"
      sha256 "fea8062fa53ba457d82c3d7d089ca38c437e1f9152aecc1029a4a270d2b44151"

      define_method(:install) do
        bin.install "specscore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/specscore/specscore-cli/releases/download/v0.15.0/specscore_0.15.0_darwin_arm64.tar.gz"
      sha256 "927269cebd89aa7faca5a43579d2f379a1187785e7744a98a776191d29ed8b80"

      define_method(:install) do
        bin.install "specscore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/specscore/specscore-cli/releases/download/v0.15.0/specscore_0.15.0_linux_amd64.tar.gz"
      sha256 "a523c2f6d690e6429972894d4e6aeff9a5deb48b8d7f4533eaa501bd8a0a8c3b"
      define_method(:install) do
        bin.install "specscore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/specscore/specscore-cli/releases/download/v0.15.0/specscore_0.15.0_linux_arm64.tar.gz"
      sha256 "b3d2b4ce0eaa9cfbd881e45e0f5beccbba2b3d2f5ced0e6b9d9fd950346a52b9"
      define_method(:install) do
        bin.install "specscore"
      end
    end
  end

  test do
    system "#{bin}/specscore", "--version"
  end
end
