# This file was generated by GoReleaser. DO NOT EDIT.
cask "specscore" do
  version "0.35.0"

  on_macos do
    on_intel do
      sha256 "aa976cbe32f2816cbd017a0a8b805a85ca64792ea952e361e1f33e41476d30a4"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "736cf7762d73e2d4c937b2f9c3eb153a06b80d974ba448476b39d07b00c30abf"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5afa0372c229b86089638eab119c75aefc020b77a22a17a19d422214d7c8acbc"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1ce7d730fd08b037d8039f3a8357e31752b320d73488e430d335794ad782c28"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "specscore"
  desc "SpecScore CLI — lint, validate, and navigate Markdown specifications."
  homepage "https://specscore.md"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specscore"

  # No zap stanza required

end
