# This file was generated by GoReleaser. DO NOT EDIT.
cask "specscore" do
  version "0.37.13"

  on_macos do
    on_arm do
      sha256 "ce1e60a51fcfc37c1497d57c57476216c770bedab44cf73a5192c6263f7092c2"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "603d45ef46cd1449612d563c24f452c26bee4fe065b944442321aa76e5a069c2"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2892ff1c409356e85e59326a0ad74775635a6a77fc8b1a011343e65a14b5cb25"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "91496b9c1f6280de8673327a3250ddc841f552307486a16ad74b9b219223f52f"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_amd64.tar.gz"
    end
  end

  name "specscore"
  desc "SpecScore CLI — lint, validate, and navigate Markdown specifications."
  homepage "https://specscore.md"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specscore"

  # No zap stanza required
end
