# This file was generated by GoReleaser. DO NOT EDIT.
cask "specscore" do
  version "0.20.2"

  on_macos do
    on_intel do
      sha256 "a1cbc6dc842a5189b737e0639a0af03364430cf6a6e92cdc1f0a9ad01724ba5a"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "638ada5cd79515f67fb127d2a9c2b573ca31798f3e2a820155524dc87d4c188e"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9feced1ff2bd4bc81350488ddabe07108af64d4020b057aba5048004c9a7c356"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b57a18b967878352c2257ce050895fd3e112ec7931cfbbc49f5065c853e1bebc"
      url "https://github.com/specscore/specscore-cli/releases/download/v#{version}/specscore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "specscore"
  desc "SpecScore CLI — lint, validate, and navigate Markdown specifications."
  homepage "https://specscore.md"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "specscore"

  # No zap stanza required

end
